### ISSUE TITLE
Wagtail 1.1 support?

### ISSUE THREAD

**Issue by tomdyson** [rfosterslo/wagtailplus#1]
Hi @rfosterslo. These modules look really good, particularly Rollbacks, which fills an obvious gap in current functionality and is close to our planned implementation in the core app. Is there any reason it's currently pinned to Wagtail 1.0?

**Comment by rfosterslo** [comment]
I need to update some URLs due to the inclusion of namespaces in the 1.1 version - should be a quick fix.

**Comment by rfosterslo** [comment]
Changes made and all tests pass with version 1.1.

**Comment by tomdyson** [comment]
Great, thanks very much, @rfosterslo.
