### ISSUE TITLE
Errors on 'Publish Version' and 'Submit Version for Moderation'

### ISSUE THREAD

**Issue by tomdyson** [rfosterslo/wagtailplus#2]
NoReverseMatch at /admin/rollback/pages/revert/29/
Reverse for 'wagtailadmin_pages_edit' with arguments '(4,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []

and

NoReverseMatch at /admin/rollback/pages/revert/29/
Reverse for 'wagtailadmin_pages_view_draft' with arguments '(4,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []

on Wagtail 1.1.

**Comment by rfosterslo** [comment]
Are you experiencing these errors with a specific version or master (wagtailplus)?  Those URL names should no longer be in the codebase.
